version: '3.9'
services:
  service:
    build: .
    container_name: 'as23env-service'
    ports:
        - '5000:80'
    environment:
        AS23_CREDENTIALS: 'admin:password'
        AS23_CONFIG: '{"empPerPosMin":2,"empPerPosMax":4,"activeUnitsMax":5,"fireDelaySec":15,"pendingDelaySec":30}'